name: process new version

on:
  push:
    branches: [ debugaction ]
env:
    FRAMEWORK_NAME: IMGA
    PODSPEC_FILE_NAME: IMGASDK
jobs:
  process:
    #prevent to execute if the commit message contains podspec version upgrade
    runs-on: macos-latest
    name: Reading version from framework
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create a file
        run: touch whatever.txt
  
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Pushes podspecfile
        with:
          commit_message: 'test commit should be tagged'
          file_pattern: 'whatever.txt'
          tagging_message: 'test2'
      # Tag 
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            tag: "test"
        


      
